export const appData = {
  "summary": {
    "scenarioCount": 160,
    "stateCount": 8,
    "productCount": 5,
    "profitablePct": 53.75,
    "readyCount": 33,
    "highWinRiskCount": 49,
    "highQaCount": 16,
    "topScenario": {
      "scenario_id": "SCN-060",
      "state": "TX",
      "channel": "Direct homeowner",
      "product": "Prepaid lease",
      "product_type": "Lease",
      "credit_band": "Prime",
      "dealer_tier": "Regional",
      "system_kw": 7.026,
      "battery_attach": "No",
      "annual_kwh": 10202,
      "project_cost": 21992.68,
      "dealer_fee_pct": 0.042,
      "funding_cost_pct": 0.05,
      "loss_reserve_pct": 0.014,
      "customer_monthly_payment": 0,
      "rate_card": "$1577/kW prepaid, 4.2% dealer fee",
      "npv": -2805.15,
      "irr_pct": -0.05,
      "contribution_margin_bps": -996.414,
      "margin_gap_bps": -1595.224,
      "competitor_gap_bps": 17.921,
      "approval_lift_pts": 18.818,
      "readiness_score": 48.764,
      "qa_defects": 4,
      "priority_score": 302.05,
      "customer_savings_year_1": 1193.73,
      "recommendation": "Raise rate or reduce dealer incentive"
    }
  },
  "productSummary": [
    {
      "product": "Operating lease",
      "avg_irr_pct": 0.162,
      "avg_npv": 35285.39,
      "avg_margin_bps": 1025.282,
      "avg_payment": 328.76,
      "ready_scenarios": 23
    },
    {
      "product": "Prepaid lease",
      "avg_irr_pct": 0.091,
      "avg_npv": 982.55,
      "avg_margin_bps": 378.46,
      "avg_payment": 0.0,
      "ready_scenarios": 9
    },
    {
      "product": "Levelized PPA",
      "avg_irr_pct": 0.062,
      "avg_npv": 4740.25,
      "avg_margin_bps": 43.168,
      "avg_payment": 169.72,
      "ready_scenarios": 1
    },
    {
      "product": "Solar plus storage loan",
      "avg_irr_pct": 0.062,
      "avg_npv": 3268.45,
      "avg_margin_bps": -69.678,
      "avg_payment": 298.42,
      "ready_scenarios": 0
    },
    {
      "product": "Solar loan",
      "avg_irr_pct": 0.056,
      "avg_npv": 915.77,
      "avg_margin_bps": -116.973,
      "avg_payment": 258.04,
      "ready_scenarios": 0
    }
  ],
  "stateSummary": [
    {
      "state": "NY",
      "avg_readiness": 67.82,
      "avg_margin_bps": 419.245,
      "avg_competitor_gap_bps": 54.502,
      "high_priority_count": 12
    },
    {
      "state": "CA",
      "avg_readiness": 66.886,
      "avg_margin_bps": 666.28,
      "avg_competitor_gap_bps": 5.077,
      "high_priority_count": 8
    },
    {
      "state": "NJ",
      "avg_readiness": 66.101,
      "avg_margin_bps": 279.205,
      "avg_competitor_gap_bps": 58.488,
      "high_priority_count": 13
    },
    {
      "state": "FL",
      "avg_readiness": 59.699,
      "avg_margin_bps": 206.325,
      "avg_competitor_gap_bps": 64.309,
      "high_priority_count": 14
    },
    {
      "state": "NV",
      "avg_readiness": 56.953,
      "avg_margin_bps": 226.357,
      "avg_competitor_gap_bps": 52.385,
      "high_priority_count": 14
    },
    {
      "state": "AZ",
      "avg_readiness": 56.25,
      "avg_margin_bps": 131.762,
      "avg_competitor_gap_bps": 37.288,
      "high_priority_count": 15
    },
    {
      "state": "CO",
      "avg_readiness": 55.587,
      "avg_margin_bps": 7.021,
      "avg_competitor_gap_bps": 53.86,
      "high_priority_count": 17
    },
    {
      "state": "TX",
      "avg_readiness": 55.271,
      "avg_margin_bps": 80.221,
      "avg_competitor_gap_bps": 34.929,
      "high_priority_count": 16
    }
  ],
  "rateCardActions": [
    {
      "scenario_id": "SCN-060",
      "state": "TX",
      "channel": "Direct homeowner",
      "product": "Prepaid lease",
      "product_type": "Lease",
      "credit_band": "Prime",
      "dealer_tier": "Regional",
      "system_kw": 7.026,
      "battery_attach": "No",
      "annual_kwh": 10202,
      "project_cost": 21992.68,
      "dealer_fee_pct": 0.042,
      "funding_cost_pct": 0.05,
      "loss_reserve_pct": 0.014,
      "customer_monthly_payment": 0,
      "rate_card": "$1577/kW prepaid, 4.2% dealer fee",
      "npv": -2805.15,
      "irr_pct": -0.05,
      "contribution_margin_bps": -996.414,
      "margin_gap_bps": -1595.224,
      "competitor_gap_bps": 17.921,
      "approval_lift_pts": 18.818,
      "readiness_score": 48.764,
      "qa_defects": 4,
      "priority_score": 302.05,
      "customer_savings_year_1": 1193.73,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-107",
      "state": "NY",
      "channel": "New homes",
      "product": "Solar plus storage loan",
      "product_type": "Loan",
      "credit_band": "Near prime",
      "dealer_tier": "Regional",
      "system_kw": 6.395,
      "battery_attach": "Yes",
      "annual_kwh": 7408,
      "project_cost": 23307.56,
      "dealer_fee_pct": 0.113,
      "funding_cost_pct": 0.061,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 222.38,
      "rate_card": "9.27% APR, 11.3% dealer fee",
      "npv": -2957.82,
      "irr_pct": 0.047,
      "contribution_margin_bps": -406.544,
      "margin_gap_bps": -1169.058,
      "competitor_gap_bps": 196.651,
      "approval_lift_pts": 5.355,
      "readiness_score": 43.949,
      "qa_defects": 6,
      "priority_score": 299.091,
      "customer_savings_year_1": -890.53,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-066",
      "state": "FL",
      "channel": "Installer platform",
      "product": "Solar plus storage loan",
      "product_type": "Loan",
      "credit_band": "Near prime",
      "dealer_tier": "Regional",
      "system_kw": 6.611,
      "battery_attach": "Yes",
      "annual_kwh": 9880,
      "project_cost": 20853.09,
      "dealer_fee_pct": 0.114,
      "funding_cost_pct": 0.062,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 202.18,
      "rate_card": "9.45% APR, 11.4% dealer fee",
      "npv": -4437.61,
      "irr_pct": 0.039,
      "contribution_margin_bps": -505.538,
      "margin_gap_bps": -1182.601,
      "competitor_gap_bps": 174.819,
      "approval_lift_pts": 6.546,
      "readiness_score": 44.11,
      "qa_defects": 5,
      "priority_score": 284.474,
      "customer_savings_year_1": -746.52,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-023",
      "state": "AZ",
      "channel": "New homes",
      "product": "Solar loan",
      "product_type": "Loan",
      "credit_band": "Near prime",
      "dealer_tier": "National",
      "system_kw": 7.6,
      "battery_attach": "No",
      "annual_kwh": 12196,
      "project_cost": 22467.89,
      "dealer_fee_pct": 0.118,
      "funding_cost_pct": 0.066,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 214.69,
      "rate_card": "9.23% APR, 11.8% dealer fee",
      "npv": -3012.64,
      "irr_pct": 0.051,
      "contribution_margin_bps": -418.429,
      "margin_gap_bps": -1190.638,
      "competitor_gap_bps": 178.002,
      "approval_lift_pts": 6.021,
      "readiness_score": 40.709,
      "qa_defects": 1,
      "priority_score": 283.985,
      "customer_savings_year_1": -380.93,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-085",
      "state": "NJ",
      "channel": "Dealer partner",
      "product": "Solar plus storage loan",
      "product_type": "Loan",
      "credit_band": "Near prime",
      "dealer_tier": "Regional",
      "system_kw": 10.293,
      "battery_attach": "Yes",
      "annual_kwh": 13529,
      "project_cost": 38637.52,
      "dealer_fee_pct": 0.119,
      "funding_cost_pct": 0.062,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 411.49,
      "rate_card": "10.60% APR, 11.9% dealer fee",
      "npv": 2872.39,
      "irr_pct": 0.07,
      "contribution_margin_bps": -192.793,
      "margin_gap_bps": -968.927,
      "competitor_gap_bps": 300.507,
      "approval_lift_pts": 8.252,
      "readiness_score": 49.106,
      "qa_defects": 6,
      "priority_score": 282.555,
      "customer_savings_year_1": -1961.5,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-068",
      "state": "FL",
      "channel": "Direct homeowner",
      "product": "Solar plus storage loan",
      "product_type": "Loan",
      "credit_band": "Near prime",
      "dealer_tier": "Regional",
      "system_kw": 7.106,
      "battery_attach": "Yes",
      "annual_kwh": 10627,
      "project_cost": 25468.69,
      "dealer_fee_pct": 0.131,
      "funding_cost_pct": 0.061,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 265.03,
      "rate_card": "10.16% APR, 13.1% dealer fee",
      "npv": -980.67,
      "irr_pct": 0.057,
      "contribution_margin_bps": -310.815,
      "margin_gap_bps": -1036.507,
      "competitor_gap_bps": 281.076,
      "approval_lift_pts": 1.536,
      "readiness_score": 43.245,
      "qa_defects": 2,
      "priority_score": 273.979,
      "customer_savings_year_1": -1373.66,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-147",
      "state": "NV",
      "channel": "New homes",
      "product": "Solar plus storage loan",
      "product_type": "Loan",
      "credit_band": "Near prime",
      "dealer_tier": "Regional",
      "system_kw": 8.529,
      "battery_attach": "Yes",
      "annual_kwh": 14758,
      "project_cost": 32504.05,
      "dealer_fee_pct": 0.126,
      "funding_cost_pct": 0.064,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 333.29,
      "rate_card": "10.02% APR, 12.6% dealer fee",
      "npv": -525.25,
      "irr_pct": 0.062,
      "contribution_margin_bps": -287.253,
      "margin_gap_bps": -938.098,
      "competitor_gap_bps": 234.235,
      "approval_lift_pts": 4.036,
      "readiness_score": 38.475,
      "qa_defects": 5,
      "priority_score": 272.685,
      "customer_savings_year_1": -1638.08,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-155",
      "state": "NV",
      "channel": "New homes",
      "product": "Levelized PPA",
      "product_type": "PPA",
      "credit_band": "Near prime",
      "dealer_tier": "Regional",
      "system_kw": 6.264,
      "battery_attach": "No",
      "annual_kwh": 10285,
      "project_cost": 17999.67,
      "dealer_fee_pct": 0.059,
      "funding_cost_pct": 0.066,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 104.63,
      "rate_card": "$0.122/kWh, 0.00% escalator",
      "npv": -5077.02,
      "irr_pct": 0.021,
      "contribution_margin_bps": -541.992,
      "margin_gap_bps": -1311.702,
      "competitor_gap_bps": -6.819,
      "approval_lift_pts": 4.993,
      "readiness_score": 38.877,
      "qa_defects": 4,
      "priority_score": 272.483,
      "customer_savings_year_1": 390.1,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-021",
      "state": "AZ",
      "channel": "Dealer partner",
      "product": "Solar loan",
      "product_type": "Loan",
      "credit_band": "Near prime",
      "dealer_tier": "Emerging",
      "system_kw": 6.913,
      "battery_attach": "Yes",
      "annual_kwh": 12091,
      "project_cost": 22888.79,
      "dealer_fee_pct": 0.121,
      "funding_cost_pct": 0.069,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 206.46,
      "rate_card": "8.49% APR, 12.1% dealer fee",
      "npv": -6666.34,
      "irr_pct": 0.034,
      "contribution_margin_bps": -610.896,
      "margin_gap_bps": -1252.295,
      "competitor_gap_bps": -70.917,
      "approval_lift_pts": 5.703,
      "readiness_score": 42.435,
      "qa_defects": 9,
      "priority_score": 271.976,
      "customer_savings_year_1": -301.05,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-045",
      "state": "TX",
      "channel": "Dealer partner",
      "product": "Solar plus storage loan",
      "product_type": "Loan",
      "credit_band": "Near prime",
      "dealer_tier": "Emerging",
      "system_kw": 6.676,
      "battery_attach": "Yes",
      "annual_kwh": 10553,
      "project_cost": 25404.96,
      "dealer_fee_pct": 0.113,
      "funding_cost_pct": 0.059,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 248.86,
      "rate_card": "9.59% APR, 11.3% dealer fee",
      "npv": -3643.14,
      "irr_pct": 0.044,
      "contribution_margin_bps": -423.353,
      "margin_gap_bps": -1139.716,
      "competitor_gap_bps": 73.076,
      "approval_lift_pts": 3.773,
      "readiness_score": 39.965,
      "qa_defects": 6,
      "priority_score": 263.525,
      "customer_savings_year_1": -1403.29,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-137",
      "state": "CO",
      "channel": "Dealer partner",
      "product": "Prepaid lease",
      "product_type": "Lease",
      "credit_band": "Near prime",
      "dealer_tier": "National",
      "system_kw": 7.371,
      "battery_attach": "No",
      "annual_kwh": 10961,
      "project_cost": 20773.56,
      "dealer_fee_pct": 0.022,
      "funding_cost_pct": 0.064,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 0,
      "rate_card": "$1470/kW prepaid, 2.2% dealer fee",
      "npv": -1353.38,
      "irr_pct": 0.013,
      "contribution_margin_bps": -509.579,
      "margin_gap_bps": -1223.069,
      "competitor_gap_bps": 0.067,
      "approval_lift_pts": 2.576,
      "readiness_score": 43.962,
      "qa_defects": 8,
      "priority_score": 262.542,
      "customer_savings_year_1": 1368.02,
      "recommendation": "Raise rate or reduce dealer incentive"
    },
    {
      "scenario_id": "SCN-121",
      "state": "CO",
      "channel": "Dealer partner",
      "product": "Solar loan",
      "product_type": "Loan",
      "credit_band": "Near prime",
      "dealer_tier": "National",
      "system_kw": 7.19,
      "battery_attach": "No",
      "annual_kwh": 10992,
      "project_cost": 24873.76,
      "dealer_fee_pct": 0.114,
      "funding_cost_pct": 0.067,
      "loss_reserve_pct": 0.027,
      "customer_monthly_payment": 255.72,
      "rate_card": "10.20% APR, 11.4% dealer fee",
      "npv": -1422.91,
      "irr_pct": 0.061,
      "contribution_margin_bps": -332.52,
      "margin_gap_bps": -1064.633,
      "competitor_gap_bps": 90.347,
      "approval_lift_pts": 4.218,
      "readiness_score": 44.652,
      "qa_defects": 7,
      "priority_score": 254.838,
      "customer_savings_year_1": -1309.9,
      "recommendation": "Raise rate or reduce dealer incentive"
    }
  ],
  "qaQueue": [
    {
      "scenario_id": "SCN-009",
      "state": "CA",
      "channel": "Dealer partner",
      "test_area": "Funding milestone",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 62.867,
      "owner": "Product"
    },
    {
      "scenario_id": "SCN-014",
      "state": "CA",
      "channel": "Installer platform",
      "test_area": "Dealer proposal sync",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 62.887,
      "owner": "Pricing"
    },
    {
      "scenario_id": "SCN-035",
      "state": "AZ",
      "channel": "New homes",
      "test_area": "Credit prequal",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 59.728,
      "owner": "Product"
    },
    {
      "scenario_id": "SCN-037",
      "state": "AZ",
      "channel": "Dealer partner",
      "test_area": "Rate card import",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 63.585,
      "owner": "Product"
    },
    {
      "scenario_id": "SCN-056",
      "state": "TX",
      "channel": "Direct homeowner",
      "test_area": "Rate card import",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 62.639,
      "owner": "Operations"
    },
    {
      "scenario_id": "SCN-063",
      "state": "FL",
      "channel": "New homes",
      "test_area": "Funding milestone",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 61.46,
      "owner": "Pricing"
    },
    {
      "scenario_id": "SCN-089",
      "state": "NJ",
      "channel": "Dealer partner",
      "test_area": "Credit prequal",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 65.854,
      "owner": "Operations"
    },
    {
      "scenario_id": "SCN-095",
      "state": "NJ",
      "channel": "New homes",
      "test_area": "Dealer proposal sync",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 60.27,
      "owner": "Pricing"
    },
    {
      "scenario_id": "SCN-121",
      "state": "CO",
      "channel": "Dealer partner",
      "test_area": "Credit prequal",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 65.721,
      "owner": "Product"
    },
    {
      "scenario_id": "SCN-124",
      "state": "CO",
      "channel": "Direct homeowner",
      "test_area": "Credit prequal",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 65.509,
      "owner": "Operations"
    },
    {
      "scenario_id": "SCN-144",
      "state": "NV",
      "channel": "Direct homeowner",
      "test_area": "Credit prequal",
      "severity": "Medium",
      "open_defects": 7,
      "data_quality_score": 63.152,
      "owner": "Analytics"
    },
    {
      "scenario_id": "SCN-002",
      "state": "CA",
      "channel": "Installer platform",
      "test_area": "Rate card import",
      "severity": "Medium",
      "open_defects": 6,
      "data_quality_score": 70.138,
      "owner": "Pricing"
    }
  ],
  "stakeholderActions": [
    {
      "action_id": "ACT-017",
      "scenario_id": "SCN-017",
      "action": "Expand into next operating review",
      "owner": "Pricing manager",
      "meeting": "S&OP",
      "estimated_margin_impact": 315199.31,
      "due_week": "2026-06-19"
    },
    {
      "action_id": "ACT-102",
      "scenario_id": "SCN-102",
      "action": "Raise rate or reduce dealer incentive",
      "owner": "Pricing manager",
      "meeting": "Weekly pricing review",
      "estimated_margin_impact": 183657.41,
      "due_week": "2026-06-12"
    },
    {
      "action_id": "ACT-069",
      "scenario_id": "SCN-069",
      "action": "Reprice to defend installer proposal flow",
      "owner": "Product lead",
      "meeting": "Product council",
      "estimated_margin_impact": 183437.81,
      "due_week": "2026-06-19"
    },
    {
      "action_id": "ACT-025",
      "scenario_id": "SCN-025",
      "action": "Raise rate or reduce dealer incentive",
      "owner": "Dealer ops",
      "meeting": "Weekly pricing review",
      "estimated_margin_impact": 170508.23,
      "due_week": "2026-06-19"
    },
    {
      "action_id": "ACT-052",
      "scenario_id": "SCN-052",
      "action": "Expand into next operating review",
      "owner": "Analytics",
      "meeting": "S&OP",
      "estimated_margin_impact": 169152.71,
      "due_week": "2026-06-05"
    },
    {
      "action_id": "ACT-049",
      "scenario_id": "SCN-049",
      "action": "Expand into next operating review",
      "owner": "Analytics",
      "meeting": "Platform QA standup",
      "estimated_margin_impact": 166735.43,
      "due_week": "2026-06-12"
    },
    {
      "action_id": "ACT-136",
      "scenario_id": "SCN-136",
      "action": "Raise rate or reduce dealer incentive",
      "owner": "Product lead",
      "meeting": "S&OP",
      "estimated_margin_impact": 158042.59,
      "due_week": "2026-06-19"
    },
    {
      "action_id": "ACT-060",
      "scenario_id": "SCN-060",
      "action": "Raise rate or reduce dealer incentive",
      "owner": "Analytics",
      "meeting": "Weekly pricing review",
      "estimated_margin_impact": 156915.34,
      "due_week": "2026-06-26"
    },
    {
      "action_id": "ACT-104",
      "scenario_id": "SCN-104",
      "action": "Raise rate or reduce dealer incentive",
      "owner": "Product lead",
      "meeting": "Product council",
      "estimated_margin_impact": 155604.83,
      "due_week": "2026-06-05"
    },
    {
      "action_id": "ACT-120",
      "scenario_id": "SCN-120",
      "action": "Expand into next operating review",
      "owner": "Dealer ops",
      "meeting": "Weekly pricing review",
      "estimated_margin_impact": 154408.81,
      "due_week": "2026-06-19"
    }
  ]
};
